<a href="https://colab.research.google.com/github/BelikMary/Data_Science_platform/blob/main/HW3_%D1%81%D1%82%D0%B0%D1%82%D0%B8%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5_%D0%B3%D0%B8%D0%BF%D0%BE%D1%82%D0%B5%D0%B7%D1%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа 3. Описательная статистика


## Ваши данные
Заполните следующую информацию:

*Имя:* Мария
*Фамилия:* Белик
*Электронная почта:* BelikMK@mgpu.ru



In [ ]:
# imports and setup
import pandas as pd
import scipy as sc
from scipy.stats import norm
import statsmodels.api as sm

import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = (10, 6)
plt.style.use('ggplot')

## Часть 3.1: Индекс качества воздуха SLC

В этой задаче изучить качество воздуха в Солт-Лейк-Сити.

### Задача 3.1.0. Узнайте об AQI

Прочтите об [индексе качества воздуха (AQI)](https://www.airnow.gov/aqi/aqi-basics) и
Система [AirNow](https://www.airnow.gov/about-airnow).


### Задача 3.1.1. Скачать данные
Агентство по охране окружающей среды предоставляет доступ к данным о качестве воздуха на веб-сайте AirData. Прочтите о данных, доступных на [этой информационной странице] (https://www.epa.gov/outdoor-air-quality-data/air-data-basic-information). Или скачайте файл `ad_viz_plotval_data.csv` в каталоге задания.


Перейдите на [website] (https://www.epa.gov/outdoor-air-quality-data/download-daily-data) и загрузите следующие ежедневные данные:

+ Pollutant = PM2.5
+ Year = 2023
+ City = Salt Lake City, UT
+ Monitor Site = All Sites

### Задача 3.1.2. Импорт данных. Предобработка данных
Используйте функцию `pandas.read_csv()` для импорта данных.

Предупреждение: эти данные не соответствуют критериям качетсва:

+ Даты не сортируются.
+ Некоторые даты могут иметь пропущенные значения.
+ Некоторые даты могут иметь несколько значений, соответствующих разным датчикам (POC=1,2,3,4,5).

In [ ]:
from google.colab import files                  #загрузка данных в колаб
uploaded = files.upload()

for fn in uploaded.keys():
  print('User upload file "{name}" witn length {length} bytes'.format(name=fn,length=len(uploaded[fn])))

Saving ad_viz_plotval_data.csv to ad_viz_plotval_data (1).csv
User upload file "ad_viz_plotval_data (1).csv" witn length 1330103 bytes


In [ ]:
#записываем данные в датафрейм

df=pd.read_csv("ad_viz_plotval_data.csv")
df

Date Source    Site ID  POC  Daily Mean PM2.5 Concentration  \
0     01/01/2023    AQS  490352005    1                             4.6   
1     01/02/2023    AQS  490352005    1                             4.0   
2     01/03/2023    AQS  490352005    1                            12.5   
3     01/04/2023    AQS  490352005    1                             9.9   
4     01/05/2023    AQS  490352005    1                             2.2   
...          ...    ...        ...  ...                             ...   
6509  12/27/2023    AQS  490450004    3                            15.5   
6510  12/28/2023    AQS  490450004    3                            17.6   
6511  12/29/2023    AQS  490450004    3                            19.3   
6512  12/30/2023    AQS  490450004    3                            26.6   
6513  12/31/2023    AQS  490450004    3                            18.7   

         UNITS  DAILY_AQI_VALUE    Site Name  DAILY_OBS_COUNT  \
0     ug/m3 LC               19  Copper View                1   
1     ug/m3 LC               17  Copper View                1   
2     ug/m3 LC               52  Copper View                1   
3     ug/m3 LC               41  Copper View                1   
4     ug/m3 LC                9  Copper View                1   
...        ...              ...          ...              ...   
6509  ug/m3 LC               58         Erda                1   
6510  ug/m3 LC               63         Erda                1   
6511  ug/m3 LC               66         Erda                1   
6512  ug/m3 LC               81         Erda                1   
6513  ug/m3 LC               65         Erda                1   

      PERCENT_COMPLETE  AQS_PARAMETER_CODE        AQS_PARAMETER_DESC  \
0                100.0               88101  PM2.5 - Local Conditions   
1                100.0               88101  PM2.5 - Local Conditions   
2                100.0               88101  PM2.5 - Local Conditions   
3                100.0               88101  PM2.5 - Local Conditions   
4                100.0               88101  PM2.5 - Local Conditions   
...                ...                 ...                       ...   
6509             100.0               88101  PM2.5 - Local Conditions   
6510             100.0               88101  PM2.5 - Local Conditions   
6511             100.0               88101  PM2.5 - Local Conditions   
6512             100.0               88101  PM2.5 - Local Conditions   
6513             100.0               88101  PM2.5 - Local Conditions   

      CBSA_CODE           CBSA_NAME  STATE_CODE STATE  COUNTY_CODE     COUNTY  \
0         41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
1         41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
2         41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
3         41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
4         41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
...         ...                 ...         ...   ...          ...        ...   
6509      41620  Salt Lake City, UT          49  Utah           45     Tooele   
6510      41620  Salt Lake City, UT          49  Utah           45     Tooele   
6511      41620  Salt Lake City, UT          49  Utah           45     Tooele   
6512      41620  Salt Lake City, UT          49  Utah           45     Tooele   
6513      41620  Salt Lake City, UT          49  Utah           45     Tooele   

      SITE_LATITUDE  SITE_LONGITUDE  
0         40.598056     -111.894167  
1         40.598056     -111.894167  
2         40.598056     -111.894167  
3         40.598056     -111.894167  
4         40.598056     -111.894167  
...             ...             ...  
6509      40.600550     -112.355780  
6510      40.600550     -112.355780  
6511      40.600550     -112.355780  
6512      40.600550     -112.355780  
6513      40.600550     -112.355780  

[6514 rows x 20 columns]

Описание данных:

1.   Date - дата
2.   Source - ресурс, датчик
3.   Site ID - идентификационный код базы данных AQS для объекта мониторинга воздуха
4.   POC - код появления параметра, идентифицирует конкретный монитор параметра на объекте
5.   Daily Mean PM2.5 Concentration - средняя дневная концентрация PM2.5
6.   UNITS - единицы измерения
7.   DAILY_AQI_VALUE -дневное значение AQI (Air Quality Index)
8.   Site Name - наименование объекта
9.   DAILY_OBS_COUNT -дневное количество наблюдений                
10.  PERCENT_COMPLETE - процент выполнения             
11.  AQS_PARAMETER_CODE - код параметра AQS, назначенный монитору в AQS              
12.  AQS_PARAMETER_DESC - Имя или описание, присвоенное в AQS параметру, измеряемому монитором. Параметры могут быть загрязняющими или незагрязняющими веществами            
13. CBSA_CODE - код основной статистической облачти                     
14. CBSA_NAME - наименование основной статистической области                      
15. STATE_CODE - код штата                       
16.  STATE - штат                         
17.  COUNTY_CODE - код страны                
18.  COUNTY - страна                           
19.  SITE_LATITUDE - угловое расстояние пункта мониторинга к северу от экватора измеряется в десятичных градусах               
20.  SITE_LONGITUDE - угловое расстояние пункта мониторинга к востоку от нулевого меридиана измеряется в десятичных градусах

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6514 entries, 0 to 6513
Data columns (total 20 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Date                            6514 non-null   object 
 1   Source                          6514 non-null   object 
 2   Site ID                         6514 non-null   int64  
 3   POC                             6514 non-null   int64  
 4   Daily Mean PM2.5 Concentration  6514 non-null   float64
 5   UNITS                           6514 non-null   object 
 6   DAILY_AQI_VALUE                 6514 non-null   int64  
 7   Site Name                       6514 non-null   object 
 8   DAILY_OBS_COUNT                 6514 non-null   int64  
 9   PERCENT_COMPLETE                6514 non-null   float64
 10  AQS_PARAMETER_CODE              6514 non-null   int64  
 11  AQS_PARAMETER_DESC              6514 non-null   object 
 12  CBSA_CODE                       65

In [ ]:
df.describe()

Site ID          POC  Daily Mean PM2.5 Concentration  \
count  6.514000e+03  6514.000000                     6514.000000   
mean   4.903637e+08     2.171323                        7.243921   
std    3.041880e+04     1.259437                        6.279512   
min    4.903520e+08     1.000000                       -0.500000   
25%    4.903530e+08     1.000000                        3.800000   
50%    4.903530e+08     2.000000                        5.700000   
75%    4.903530e+08     3.000000                        7.900000   
max    4.904500e+08     5.000000                       52.600000   

       DAILY_AQI_VALUE  DAILY_OBS_COUNT  PERCENT_COMPLETE  AQS_PARAMETER_CODE  \
count      6514.000000           6514.0            6514.0              6514.0   
mean         28.064784              1.0             100.0             88101.0   
std          19.298589              0.0               0.0                 0.0   
min           0.000000              1.0             100.0             88101.0   
25%          16.000000              1.0             100.0             88101.0   
50%          24.000000              1.0             100.0             88101.0   
75%          33.000000              1.0             100.0             88101.0   
max         143.000000              1.0             100.0             88101.0   

       CBSA_CODE  STATE_CODE  COUNTY_CODE  SITE_LATITUDE  SITE_LONGITUDE  
count     6514.0      6514.0  6514.000000    6514.000000     6514.000000  
mean     41620.0        49.0    36.105312      40.685918     -111.987452  
std          0.0         0.0     3.135747       0.097821        0.143387  
min      41620.0        49.0    35.000000      40.496392     -112.355780  
25%      41620.0        49.0    35.000000      40.600550     -112.036298  
50%      41620.0        49.0    35.000000      40.709762     -111.931000  
75%      41620.0        49.0    35.000000      40.777145     -111.894167  
max      41620.0        49.0    45.000000      40.807897     -111.872222

In [ ]:
#меняем тип данных даты с object на datatime

df['Date'] = pd.to_datetime(df['Date'])
print(df['Date'].dtypes)

datetime64[ns]


In [ ]:
#сортируем по дате

df.sort_values(['Date'])

Date Source    Site ID  POC  Daily Mean PM2.5 Concentration  \
0    2023-01-01    AQS  490352005    1                             4.6   
4340 2023-01-01    AQS  490353015    3                             2.8   
4705 2023-01-01    AQS  490353016    1                             0.8   
3987 2023-01-01    AQS  490353015    1                             3.5   
1080 2023-01-01    AQS  490353006    2                             6.8   
...         ...    ...        ...  ...                             ...   
4704 2023-12-31    AQS  490353015    3                            26.8   
5069 2023-12-31    AQS  490353016    1                            24.4   
5434 2023-12-31    AQS  490354002    1                            32.9   
2891 2023-12-31    AQS  490353010    3                            27.8   
6513 2023-12-31    AQS  490450004    3                            18.7   

         UNITS  DAILY_AQI_VALUE              Site Name  DAILY_OBS_COUNT  \
0     ug/m3 LC               19            Copper View                1   
4340  ug/m3 LC               12  Utah Technical Center                1   
4705  ug/m3 LC                3            Inland Port                1   
3987  ug/m3 LC               15  Utah Technical Center                1   
1080  ug/m3 LC               28              Hawthorne                1   
...        ...              ...                    ...              ...   
4704  ug/m3 LC               82  Utah Technical Center                1   
5069  ug/m3 LC               77            Inland Port                1   
5434  ug/m3 LC               95              Near Road                1   
2891  ug/m3 LC               84              ROSE PARK                1   
6513  ug/m3 LC               65                   Erda                1   

      PERCENT_COMPLETE  AQS_PARAMETER_CODE        AQS_PARAMETER_DESC  \
0                100.0               88101  PM2.5 - Local Conditions   
4340             100.0               88101  PM2.5 - Local Conditions   
4705             100.0               88101  PM2.5 - Local Conditions   
3987             100.0               88101  PM2.5 - Local Conditions   
1080             100.0               88101  PM2.5 - Local Conditions   
...                ...                 ...                       ...   
4704             100.0               88101  PM2.5 - Local Conditions   
5069             100.0               88101  PM2.5 - Local Conditions   
5434             100.0               88101  PM2.5 - Local Conditions   
2891             100.0               88101  PM2.5 - Local Conditions   
6513             100.0               88101  PM2.5 - Local Conditions   

      CBSA_CODE           CBSA_NAME  STATE_CODE STATE  COUNTY_CODE     COUNTY  \
0         41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
4340      41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
4705      41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
3987      41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
1080      41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
...         ...                 ...         ...   ...          ...        ...   
4704      41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
5069      41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
5434      41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
2891      41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
6513      41620  Salt Lake City, UT          49  Utah           45     Tooele   

      SITE_LATITUDE  SITE_LONGITUDE  
0         40.598056     -111.894167  
4340      40.777145     -111.945849  
4705      40.807897     -112.087717  
3987      40.777145     -111.945849  
1080      40.736389     -111.872222  
...             ...             ...  
4704      40.777145     -111.945849  
5069      40.807897     -112.087717  
5434      40.662961     -111.901851  
289

In [ ]:
#дополнительная проверка, что нулевых значений нет

null_count = df.isnull().sum()
print(null_count)

Date                              0
Source                            0
Site ID                           0
POC                               0
Daily Mean PM2.5 Concentration    0
UNITS                             0
DAILY_AQI_VALUE                   0
Site Name                         0
DAILY_OBS_COUNT                   0
PERCENT_COMPLETE                  0
AQS_PARAMETER_CODE                0
AQS_PARAMETER_DESC                0
CBSA_CODE                         0
CBSA_NAME                         0
STATE_CODE                        0
STATE                             0
COUNTY_CODE                       0
COUNTY                            0
SITE_LATITUDE                     0
SITE_LONGITUDE                    0
dtype: int64


In [ ]:
#проверка того, что в одну дату проведены несколько измерений с разных датчиков и на разных объектах

duplicateRows = df[df.duplicated(['Date'])]
duplicateRows

Date Source    Site ID  POC  Daily Mean PM2.5 Concentration  \
360  2023-01-01    AQS  490352005    4                             5.3   
361  2023-01-02    AQS  490352005    4                             4.1   
362  2023-01-03    AQS  490352005    4                            13.4   
363  2023-01-04    AQS  490352005    4                             8.8   
364  2023-01-05    AQS  490352005    4                             2.2   
...         ...    ...        ...  ...                             ...   
6509 2023-12-27    AQS  490450004    3                            15.5   
6510 2023-12-28    AQS  490450004    3                            17.6   
6511 2023-12-29    AQS  490450004    3                            19.3   
6512 2023-12-30    AQS  490450004    3                            26.6   
6513 2023-12-31    AQS  490450004    3                            18.7   

         UNITS  DAILY_AQI_VALUE    Site Name  DAILY_OBS_COUNT  \
360   ug/m3 LC               22  Copper View                1   
361   ug/m3 LC               17  Copper View                1   
362   ug/m3 LC               54  Copper View                1   
363   ug/m3 LC               37  Copper View                1   
364   ug/m3 LC                9  Copper View                1   
...        ...              ...          ...              ...   
6509  ug/m3 LC               58         Erda                1   
6510  ug/m3 LC               63         Erda                1   
6511  ug/m3 LC               66         Erda                1   
6512  ug/m3 LC               81         Erda                1   
6513  ug/m3 LC               65         Erda                1   

      PERCENT_COMPLETE  AQS_PARAMETER_CODE        AQS_PARAMETER_DESC  \
360              100.0               88101  PM2.5 - Local Conditions   
361              100.0               88101  PM2.5 - Local Conditions   
362              100.0               88101  PM2.5 - Local Conditions   
363              100.0               88101  PM2.5 - Local Conditions   
364              100.0               88101  PM2.5 - Local Conditions   
...                ...                 ...                       ...   
6509             100.0               88101  PM2.5 - Local Conditions   
6510             100.0               88101  PM2.5 - Local Conditions   
6511             100.0               88101  PM2.5 - Local Conditions   
6512             100.0               88101  PM2.5 - Local Conditions   
6513             100.0               88101  PM2.5 - Local Conditions   

      CBSA_CODE           CBSA_NAME  STATE_CODE STATE  COUNTY_CODE     COUNTY  \
360       41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
361       41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
362       41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
363       41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
364       41620  Salt Lake City, UT          49  Utah           35  Salt Lake   
...         ...                 ...         ...   ...          ...        ...   
6509      41620  Salt Lake City, UT          49  Utah           45     Tooele   
6510      41620  Salt Lake City, UT          49  Utah           45     Tooele   
6511      41620  Salt Lake City, UT          49  Utah           45     Tooele   
6512      41620  Salt Lake City, UT          49  Utah           45     Tooele   
6513      41620  Salt Lake City, UT          49  Utah           45     Tooele   

      SITE_LATITUDE  SITE_LONGITUDE  
360       40.598056     -111.894167  
361       40.598056     -111.894167  
362       40.598056     -111.894167  
363       40.598056     -111.894167  
364       40.598056     -111.894167  
...             ...             ...  
6509      40.600550     -112.355780  
6510      40.600550     -112.355780  
6511      40.600550     -112.355780  
6512      40.600550     -112.355780  
6513      40.600550     -112.355780  

[6149 rows x 20 columns]

### Задача 3.1.3. Визуализация данные

1. Данные содержат несколько записей о концентрации PM2,5 и AQI на одну и ту же дату, измеренных на разных объектах и с помощью разных датчиков (POCS). Постройте средние значения PM2,5 и AQI относительно даты на одном графике. Все, кто анализирует график, должен уметь определять: какова средняя концентрация PM 2,5 или значение AQI на конкретную дату.


*Подсказка*: использовать функцию `pandas groupby`.


In [ ]:
#создание нового датафрейма, который содержит дату и средние значения PM2,5 и AQI в этот день.

df1=df['Daily Mean PM2.5 Concentration'].groupby(df['Date']).mean().reset_index(name='Mean PM2,5')
df2=df['DAILY_AQI_VALUE'].groupby(df['Date']).mean().reset_index(name='Mean AQI')
dfplot=pd.merge(df1,df2,on='Date',how='inner')

In [ ]:
dfplot

Date  Mean PM2,5   Mean AQI
0   2023-01-01    3.494444  14.611111
1   2023-01-02    2.638889  11.000000
2   2023-01-03    9.661111  40.111111
3   2023-01-04    7.277778  30.277778
4   2023-01-05    2.538889  10.555556
..         ...         ...        ...
360 2023-12-27   15.311111  57.722222
361 2023-12-28   22.400000  72.666667
362 2023-12-29   24.122222  76.222222
363 2023-12-30   25.472222  77.888889
364 2023-12-31   26.683333  81.722222

[365 rows x 3 columns]

Данных очень много, при этом по условию задачи средняя концентрация PM2,5 и знчаения AQI должны быть видны на любую конкретную дату. Возник вопрос, как реализовать эту "интерактивность", и в интернете я нашла библиотеку plotly, которая позволяет это сделать несильно сложно, красиво и понятно. Я надеюсь, так можно....

In [ ]:
#установка plotly

%pip install plotly

In [ ]:
#импортируем библиотеку для создания интерактиного графика

import plotly.express as px
import plotly.graph_objects as go

In [ ]:
#создание основного графика, чтобы отражались значения с периодом в месяц
fig = px.line(dfplot, x="Date", y=dfplot.columns,
              hover_data={"Date": "|%B %d, %Y"},
              color_discrete_sequence=px.colors.qualitative.Alphabet,
              title='График "Средние значения PM2,5 и AQI относительно даты"')

#настройка оси времени, чтобы при приближении увеличивался масштаб (т.е. сначала отображаются месяцы, затем недели месяца, затем дни)
fig.update_xaxes(
    rangeslider_visible=True,
    tickformatstops = [
        dict(dtickrange=[86400000, 604800000], value="%e %b"),
        dict(dtickrange=[604800000, "M1"], value="%e %b"),
        dict(dtickrange=["M1", "M12"], value="%b %y")
    ]
)

#создание нижней шкалы даты, с помощью которой можно "менять масштаб", приближать график условно
fig.update_xaxes(rangeslider_visible=True)

fig.show()

#чтобы узнать точные значения в конкретную дату, достаточно навести мышку на эту точку линии

* Значения AQI в основном в диапозоне от 5 до 50, а значения PM2,5 не превосходят 12, что означает удовлетворительное качество воздуха с незначительным уровнем загрязнения.
* Однако есть и выбросы (AQI от 51 до 100; PM2,5 от 12,1 до 30), что означает приемлемое качество воздуха.
* Лишь в один день (4 февраля 2023 года) значение AQI достигло 118,6, а значение PM2,5 - 40,5, что означает, что уровень загрязненности воздуха представлял риск для наиболее чувствительной части населения.

### Задача 3.1.3. Визуализация данные

2. Постройте график зависимости средней концентрации PM 2,5 от даты для двух разных участков (идентификаторы участков — 490352005 и 490353015). Обратите внимание, что в этом случае среднее значение берется по POC. Резудбьтаты для обоих участков должны быть на одном рисунке.
*Подсказка*: использовать функцию `pandas groupby`.


In [ ]:
#создание нового датафрейма, где значения только для двух участков

df111=df[['Date','Site ID','Daily Mean PM2.5 Concentration']].loc[(df['Site ID']==490352005)|(df['Site ID']==490353015)]
df111=df111.groupby(['Site ID','Date']).mean().reset_index()
df111

Site ID       Date  Daily Mean PM2.5 Concentration
0    490352005 2023-01-01                            4.95
1    490352005 2023-01-02                            4.05
2    490352005 2023-01-03                           12.95
3    490352005 2023-01-04                            9.35
4    490352005 2023-01-05                            2.20
..         ...        ...                             ...
725  490353015 2023-12-27                           13.95
726  490353015 2023-12-28                           23.40
727  490353015 2023-12-29                           27.85
728  490353015 2023-12-30                           28.85
729  490353015 2023-12-31                           28.30

[730 rows x 3 columns]

In [ ]:
#создание основного графика, чтобы отражались значения с периодом в месяц
fig = px.line(df111, x="Date", y=df111['Daily Mean PM2.5 Concentration'],color=df111['Site ID'],
              hover_data={"Date": "|%B %d, %Y"},
              color_discrete_sequence=px.colors.qualitative.Alphabet,
              title='График зависимости средней концентрации PM 2,5 от даты для двух разных участков')

#настройка оси времени, чтобы при приближении увеличивался масштаб (т.е. сначала отображаются месяцы, затем недели месяца, затем дни)
fig.update_xaxes(
    rangeslider_visible=True,
    tickformatstops = [
        dict(dtickrange=[86400000, 604800000], value="%e %b"),
        dict(dtickrange=[604800000, "M1"], value="%e %b"),
        dict(dtickrange=["M1", "M12"], value="%b %y")
    ]
)

#создание нижней шкалы даты, с помощью которой можно "менять масштаб", приближать график условно
fig.update_xaxes(rangeslider_visible=True)

fig.show()

* На графике видно, что разницы показтеля PM2,5 на рассматриваемых участках практически нет. Значит, уровень загрязненности на этих двух участнках почти одинаковый.
* Значения параметра PM2,5 в основном не превышают норму на этих участках, значит уровень загрязненности воздуха там удовлетворительный или с незначительной загрязненностью.
* Также, как и на прошлом графике, видно, что единственный день отличается загрязненностью достаточно выше нормы (PM2,5>35) - 4 февраля 2023 года.

### Задача 3.1.4. Постройте скользящее среднее

Постройте график с дневным значением AQI и скользящим средним для дневного значения AQI. Используйте дневное значение AQI, усредненное по сайтам и POC. Поэкспериментируйте с разными временными диапазонами, чтобы найти наиболее подходящее.

*Подсказка:* Используйте `rolling()`.

In [ ]:
#создаем новый датафрейм только с теми столбцами, которые нужны

df314=df[['Date','DAILY_AQI_VALUE']]
df314=df314.groupby(['Date'])['DAILY_AQI_VALUE'].mean().reset_index(name='Daily_AQI').round()
df314

Date  Daily_AQI
0   2023-01-01       15.0
1   2023-01-02       11.0
2   2023-01-03       40.0
3   2023-01-04       30.0
4   2023-01-05       11.0
..         ...        ...
360 2023-12-27       58.0
361 2023-12-28       73.0
362 2023-12-29       76.0
363 2023-12-30       78.0
364 2023-12-31       82.0

[365 rows x 2 columns]

In [ ]:
#скользящее среднее с окном в 7 дней
df314['SMA_7'] = df314['Daily_AQI'].transform ( lambda x:x.rolling(7, 7).mean()).round(1)

#скользящее среднее с окном в 30 дней
df314['SMA_30'] = df314['Daily_AQI'].transform ( lambda x:x.rolling(30, 15).mean()).round(1)
df314

Date  Daily_AQI  SMA_15  SMA_30  SMA_7
0   2023-01-01       15.0     NaN     NaN    NaN
1   2023-01-02       11.0     NaN     NaN    NaN
2   2023-01-03       40.0     NaN     NaN    NaN
3   2023-01-04       30.0     NaN     NaN    NaN
4   2023-01-05       11.0     NaN     NaN    NaN
..         ...        ...     ...     ...    ...
360 2023-12-27       58.0    38.1    44.6   38.1
361 2023-12-28       73.0    40.9    44.6   40.9
362 2023-12-29       76.0    44.7    44.3   44.7
363 2023-12-30       78.0    52.1    44.2   52.1
364 2023-12-31       82.0    62.1    44.9   62.1

[365 rows x 5 columns]

In [ ]:
#создание графиков для отображения скользящих средних

fig = px.line(df314, x="Date", y=df314[['SMA_7','SMA_30']].columns,
              hover_data={"Date": "|%B %d, %Y"},
              color_discrete_sequence=px.colors.qualitative.Alphabet,
              title='График с дневным значением AQI и скользящим средним для дневного значения AQI')

#создание столбчатой диаграммы для ссреднего дневного значения AQI
fig.add_trace(go.Bar(
    name="Daily AQI",
    x=df314['Date'], y=df314['Daily_AQI'],xhoverformat="Q%q",
    hovertemplate="%{y}%{_xother}", marker_color='#fac5b8'
))

#настройка оси времени, чтобы при приближении увеличивался масштаб (т.е. сначала отображаются месяцы, затем недели месяца, затем дни)
fig.update_xaxes(
    rangeslider_visible=True,
    tickformatstops = [
        dict(dtickrange=[86400000, 604800000], value="%e %b"),
        dict(dtickrange=[604800000, "M1"], value="%e %b"),
        dict(dtickrange=["M1", "M12"], value="%b %y")
    ]
)

#создание нижней шкалы даты, с помощью которой можно "менять масштаб", приближать график условно
fig.update_xaxes(rangeslider_visible=True)

fig.show()

## Часть 3.2. A/B-тестирование

Сначала прочитайте статью WIRED об A/B-тестировании [здесь] (http://www.wired.com/2012/04/ff_abtesting/).

Предположим, ваша компания разрабатывает новый логотип. Художественный отдел разрабатывает два логотипа: ‘Logo A’ и ‘Logo B’, показанные ниже.
![](http://www.wired.com/wiredenterprise/wp-content/gallery/20-05/ff_abtesting_f.jpg)

Ваша задача — выяснить, какой логотип лучше.


Вы решаете провести следующий эксперимент. Вы используете рекламу Google, чтобы купить 6000 рекламных объявлений. В $N_A=3000$ объявлений (выбранных случайно) вы используете логотип А, а в остальных $N_B=3000$ объявлениях вы используете логотип Б. Затем вы видите, какой логотип привлекает больше кликов.

Оказывается, $n_A=800$ зрителей с логотипом A нажимают на рекламу, а $n_B=1000$ зрителей с логотипом B нажимают на рекламу. Очевидно, что логотип B показал лучшие результаты в этом тесте, но достаточно ли разница, чтобы сказать, что логотип B лучше? Или, возможно, ‘Logo B’ просто повезло в этом тесте?

Целью этого упражнения будет проведение двухпропорционального z-теста, чтобы определить, лучше ли ‘Logo B’. Шаги будут аналогичны шагам, использованным в эксперименте Солка с полиовакциной в 1954 году (1954 Salk polio-vaccine experiment).


### Задача 3.2.1. Сформулируйте нулевую гипотезу

Пусть $p_A = n_A/N_A$ — доля кликов по логотипу A, и аналогично $p_B$ — доля кликов по логотипу B. В терминах $p_A$ и $p_B$ четко сформулируйте нулевую и альтернативную гипотезы.

**Ваше решение:**

Пусть $p_A$ и  $p_B$— доли кликов по логотипу A и по логотипу B соответственно. Тогда нулевая гипотеза состоит в том, что
$$
H_0\colon p_A \leq p_B,
$$
то есть логотип В более привлекательный.
Альтернативная гипотеза состоит в том, что
$$
H_a\colon p_A  > p_B,
$$
то есть зритель с большей вероятностью кликнет по рекламе с логотипом А, а не В.
Если брать пример с эксперимента Солка с полиовакциной,тогда и здесь уровень значимости зададим $\alpha = 0,01$.

### Задача 2.2. Найдите двухпропорциональное z-значение

Предполагая нулевую гипотезу, мы знаем, что статистика, называемая *двухпропорциональным z-значением*,
$$
Z = \frac{p_A - p_B}{\sqrt{\hat{p} \hat{q} \left( \frac{1}{N_A} + \frac{1}{N_B} \right)}}.
$$
приблизительно распределяется в соответствии со стандартным нормальным распределением. Здесь $\hat{p} = \frac{N_A}{N_A + N_B}p_A + \frac{N_B}{N_A + N_B}p_B$ и $\hat{q} = 1-\hat{p}$.


Найдите двухпропорциональное z-значение.

In [ ]:
import numpy as np

Na=3000 #число испытаний выборка А
Nb=3000 # число испытаний выборка В
na=800 # число успехов выборка А
nb=1000 # число успехов выборка В
pa=na/Na # оценка вероятности успеха выборка А
pb=nb/Nb # оценка вероятности успеха выборка В
p=(na+nb)/(Na+Nb) # оценка вероятности успеха выборка А+В

z=(pa-pb)/((p*(1-p)*((1/Na)+(1/Nb)))**0.5)
print(z)

-5.6343616981901095


### Задача 2.3. Завершите z-тест двух пропорций

Найдите значение $p$ для проверки гипотезы. Сначала, используя обычную функцию `cdf`, а затем проверьте свой ответ, запустив z-тест двух пропорций в Python с помощью  `proportions_ztest`.

In [ ]:
p_value=norm.cdf(z)
print(['{:.12f}'.format(a) for a in (z,p_value)])

['-5.634361698190', '0.000000008785']


In [ ]:
z1, p_value1=sm.stats.proportions_ztest([na,nb],[Na,Nb])
print(['{:12}'.format(b) for b in (z1,p_value1)])
kh=p_value1<0.01
print(kh)

['-5.6343616981901095', '1.7570790152024724e-08']
True


p-значение меньше уровня значимости, значит отвергаем нулевую гипотезу, а значит получаем, что зритель с большей вероятностью кликнет по рекламе с логотипом А, а не В.